# Generated by Django 4.1.3 on 2022-12-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_updated_position',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
