# Generated by Django 4.1.3 on 2022-12-01 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_customuser_last_updated_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='last_updated_position',
            new_name='position_timestamp',
        ),
    ]
