# Generated by Django 4.1.3 on 2022-11-10 02:56

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='routestop',
            name='unique_stop_number',
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('stop_number', 'route'), name='unique_stop_number'),
        ),
    ]
