# Generated by Django 4.1.3 on 2022-11-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0002_remove_routestop_unique_stop_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulestop',
            name='heavy_bag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulestop',
            name='no_bags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulestop',
            name='no_papers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedulestop',
            name='received_bags',
            field=models.DecimalField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='schedulestop',
            name='received_palets',
            field=models.DecimalField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], decimal_places=0, default=0, max_digits=5),
        ),
    ]
