# Generated by Django 4.1.3 on 2022-11-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0003_schedulestop_heavy_bag_schedulestop_no_bags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulestop',
            name='feedback_note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
