# Generated by Django 4.1.3 on 2022-11-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0004_schedulestop_feedback_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='durations',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='schedule'),
        ),
        migrations.AddField(
            model_name='schedulestop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stop'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles'),
        ),
    ]
