# Generated by Django 4.1.3 on 2022-12-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0005_route_durations_schedule_image_schedulestop_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='time_to_stop',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='last_eta_update_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
