# Generated by Django 4.1.3 on 2022-12-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0006_routestop_time_to_stop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulestop',
            name='eta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
