# Generated by Django 4.1.3 on 2022-12-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0007_alter_schedulestop_eta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulestop',
            name='eta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
