# Generated by Django 4.1.3 on 2022-12-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0008_alter_schedulestop_eta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routestop',
            old_name='time_to_stop',
            new_name='eta',
        ),
    ]
