# Generated by Django 4.1.3 on 2022-12-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0009_rename_time_to_stop_routestop_eta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulestop',
            name='received_palets',
            field=models.DecimalField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], decimal_places=0, default=0, max_digits=5),
        ),
    ]
